import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { getAuthenticatedUserRole } from "@/lib/supabase/auth-helper";
import { dbCreateStudent } from "@/lib/supabase/db-students";
import type { Student, StudentStatus } from "@/lib/types";

export async function POST(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const auth = await getAuthenticatedUserRole();
    if (auth.role === "Guest") {
      return NextResponse.json({ error: "Unauthorized: Please log in." }, { status: 401 });
    }

    const { id } = await params;
    const body = await req.json();
    const supabase = createAdminClient();

    // 1. Fetch application details
    const { data: app, error: appError } = await supabase
      .from("admission_applications")
      .select("*")
      .eq("id", id)
      .single();

    if (appError || !app) {
      return NextResponse.json({ error: "Application not found" }, { status: 404 });
    }

    if (app.status === "admitted") {
      return NextResponse.json(
        { error: "Student is already admitted", studentId: app.admitted_student_id },
        { status: 400 }
      );
    }

    const assignedSection = body.section || app.target_section || "A";
    const assignedRoll = body.roll ? parseInt(body.roll) : (app.target_roll || 1);
    const assignedClass = body.class || app.target_class || "V";
    const feeAmount = body.feeAmount !== undefined ? parseFloat(body.feeAmount) : (app.fee_amount || 0);
    const feePaid = body.feePaid !== undefined ? !!body.feePaid : true;
    const paymentReceiptNo = body.paymentReceiptNo || `REC-${Date.now().toString().slice(-6)}`;
    const currentYear = new Date().getFullYear();

    // 2. Prepare new student data
    const studentInput: Omit<Student, "id"> = {
      schoolId: "", // Will be auto-generated by dbCreateStudent
      name: app.student_name,
      photoUrl: app.photo_url || undefined,
      gender: app.gender || "Male",
      dob: app.date_of_birth || `${currentYear - 10}-01-01`,
      fatherName: app.father_name || "N/A",
      motherName: app.mother_name || "N/A",
      guardianName: app.guardian_name || app.father_name || "N/A",
      studentContact: app.student_contact || undefined,
      altMobile: app.alt_mobile || undefined,
      email: app.email || undefined,
      address: app.address || app.village || "Vill",
      pincode: app.pincode || undefined,
      religion: app.religion || "Islam",
      socialCategory: app.social_category || "General",
      casteCertificateNo: app.caste_certificate_no || undefined,
      aadhaar: app.aadhaar || undefined,
      bloodGroup: app.blood_group || undefined,
      previousSchool: app.previous_school || undefined,

      presentClass: assignedClass,
      presentSection: assignedSection,
      presentRoll: assignedRoll,
      admissionNo: body.admissionNo || undefined,
      currentStatus: "Continuing" as StudentStatus,
      admissionYear: currentYear,
      admissionDate: new Date().toISOString().split("T")[0],
      presentClassAdmissionDate: new Date().toISOString().split("T")[0],
      kanyashreeId: app.kanyashree_id || undefined,
      relationshipWithGuardian: app.relationship_with_guardian || (app.guardian_name === app.father_name ? "Father" : app.guardian_name === app.mother_name ? "Mother" : undefined),
      reAdmissionStatus: "admitted",
      reAdmittedAt: new Date().toISOString(),
      reAdmittedSession: String(currentYear),
      isInvoiceQueued: true,

      academicHistory: [
        {
          year: currentYear,
          class: assignedClass,
          section: assignedSection,
          roll: assignedRoll,
          status: "Continuing" as StudentStatus,
        },
      ],
    };

    // 3. Create student in main directory
    const createdStudent = await dbCreateStudent(studentInput);

    // 4. Update application status
    await supabase
      .from("admission_applications")
      .update({
        status: "admitted",
        admitted_student_id: createdStudent.id,
        admitted_class: assignedClass,
        admitted_section: assignedSection,
        admitted_roll: assignedRoll,
        fee_paid: feePaid,
        fee_amount: feeAmount,
        payment_receipt_no: paymentReceiptNo,
        admitted_at: new Date().toISOString(),
        admitted_by: body.admittedBy || "Teacher",
        updated_at: new Date().toISOString(),
      })
      .eq("id", id);

    // 5. Record invoice in admission_invoices table
    if (paymentReceiptNo && typeof paymentReceiptNo === "string" && paymentReceiptNo.trim()) {
      try {
        await supabase.from("admission_invoices").upsert(
          {
            invoice_number: paymentReceiptNo.trim(),
            academic_session: `${currentYear} – ${currentYear + 1}`,
            issue_date: new Date().toISOString().split("T")[0],
            issue_time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", hour12: true }),
            student_id: createdStudent.schoolId || createdStudent.id,
            student_name: app.student_name,
            student_class: assignedClass,
            section: assignedSection,
            roll_no: String(assignedRoll),
            guardian_name: app.guardian_name || app.father_name || null,
            contact_number: app.student_contact || app.alt_mobile || null,
            total_amount: Number(feeAmount) || 0,
            payment_mode: "Cash",
            payment_status: feePaid ? "Paid" : "Due",
            remarks: `New Admission Fee (${currentYear})`,
            generator_mode: "single",
            copy_type: "both",
            is_blank: false,
            invoice_status: "active",
            updated_at: new Date().toISOString(),
          },
          { onConflict: "invoice_number" }
        );
      } catch (invErr) {
        console.warn("Could not record admission invoice:", invErr);
      }
    }

    return NextResponse.json({
      success: true,
      studentId: createdStudent.id,
      schoolId: createdStudent.schoolId,
      message: `Student successfully admitted to Class ${assignedClass}, Section ${assignedSection}, Roll ${assignedRoll}`,
    });
  } catch (err: any) {
    console.error("Error admitting student from application:", err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
